### ISSUE TITLE
Database creation error

### ISSUE THREAD

**Issue by lapnd** [colisee/docker-librebooking#8]
Hi
Thank for your project.
I tried to start the project with simple docker-compose as you mentioned in README.
However, when setting up system, I always see this error
![Screenshot from 2023-03-14 22-03-52](https://user-images.githubusercontent.com/17825933/225044755-f9c984de-1854-42b0-b258-b868c995bf31.png)

I have set `MYSQL_ROOT_PASSWORD` and `LB_DB_USER_PWD` to be the same.
Can you help to give few hints on what was wrong?
Thank you!

**Comment by colisee** [comment]
Hi,
Thank you for your interest.

I tried the simple setup and I had no issues...

Here is my docker-compose.yml file
```
version: "3.7"

services:
  db:
    image: linuxserver/mariadb
    container_name: librebooking-db
    restart: always
    networks:
      - net
    volumes:
      - vol-db:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - MYSQL_DATABASE=librebooking
      - MYSQL_ROOT_PASSWORD=lapnd
      - MYSQL_USER=lb_user
      - MYSQL_PASSWORD=lapnd
  app:
    image: colisee/librebooking
    container_name: librebooking
    restart: always
    depends_on:
      - db
    networks:
      - net
    ports:
      - "8080:80"
    volumes:
      - vol-app:/var/www/html
    environment: 
      - TZ=Europe/Zurich
      - LB_DB_HOST=db
      - LB_DB_NAME=librebooking
      - LB_INSTALL_PWD=lapnd
      - LB_DB_USER=lb_user
      - LB_DB_USER_PWD=lapnd

volumes:
  vol-db:
    name: librebooking-db_data
  vol-app:
    name: librebooking_html

networks:
  net:
    name: librebooking
```

Could you please try the following:
```
docker-compose down
docker volume rm librebooking-db_data librebooking_html
# Replace your docker-compose.yml file with mine
docker-compose up --detach
# Setup the application by pointing your browser to http://localhost:8080/Web/install
```

If it still fails, could you give me some more info on your host environment?
